template: |
  
  
  Human: The following "text snippet" will be quoted in an article using the Chicago Manual of Style. Using the given information from scientific paper, rewrite the "text snippet" into quote format by adding in any clarifying information in square brackets. The information should answer the questions below. Write as if you were an expert scientist in the field of natural language processing.

  Information from the paper:
  {% for evidence in unique_evidence %}
  {% if evidence["section"] %}Section Header: "{{ evidence["section"] }}"{% endif %}
  Paragraph: "{{evidence["paragraph"]}}"
  {% endfor %}
  Text snippet: "{{sentence}}"

  Instructions:

  Using the given information, rewrite the text snippet into quote format. Specifically, add clarifying information that answers the following questions based only on the given information from the paper.

  Questions:
  {% for question in questions %}* {{question['question']}}
  {% endfor %}
  Add the clarifying information between square brackets.
  For example: the snippet "Our approach performs well" becomes "[REF0's] approach [bidirectional language modeling] performs well".
  For example: the snippet "Our task is MT" becomes "[REF0's] task is MT [machine translation]."
  The rewritten snippet should still be easy to read, so you don't have to include all of the information in the answers verbatim.


  After adding clarifying information:
  * Replace first-person pronouns with a placeholder. Replace "we" and "the authors" with "[REF0]" and "our" and "the authors'" with "[REF0's]".
  * Remove discourse markers (like "in conclusion", "in this section", "for instance", etc.)
  * Remove any references to Figures ("FIGREF") and Tables ("TABREF")
  * Fix the grammar

  Note: Keep the language in the rewritten snippet close to the original snippet. Any information that is already in the snippet should not be put inside square brackets.

  Rewrite this snippet according to the instructions and the given information.
  Text snippet: "{{sentence}}"
  

  Assistant: Here is my attempt at rewriting the text snippet:
