template: |
  The following text snippet is extracted from a scientific paper. Incorporate the answers to the following questions to clarify the snippet. Base the clarifications on the given information.

  Information:
  {% for evidence in unique_evidence %}
  {% if evidence["section"] %}Section Header: "{{ evidence["section"] }}"{% endif %}
  Paragraph: "{{evidence["paragraph"]}}"
  {% endfor %}
  {% for question in questions %}* {{question['question']}}
  {% endfor %}
  Text snippet: "{{sentence}}"

  Instructions:
  Rewrite the text snippet to incorporate the answers to the questions based on the paragraphs. If a question cannot be answered, ignore it.

  Additionally:
  * Replace first-person pronoun "we" with "[REF0]" and "our" with "[REF0's]".
  * All of the answers added should be between square brackets "[]"
  * Remove any references to Figures ("FIGREF") and Tables ("TABREF")
  For example: the snippet "Our approach performs well" becomes "[REF0's] approach [bidirectional language modeling] performs well".

  Rewrite: