template: |
  The following "text snippet" will be quoted in an article using the Chicago Manual of Style. Using the given information from scientific paper, rewrite the "text snippet" into quote format by adding in any clarifying information in square brackets. Write as if you were an expert scientist in the field of natural language processing.

  Information from the paper:

  Title: "{{title}}"

  Abstract: "{{abstract}}"
  {% if context_section_header %}
  Header of section with the snippet: "{{context_section_header}}"
  {% endif %}
  Paragraph with the snippet: "{{context_paragraph}}"

  Text snippet: "{{sentence}}"

  Instructions:

  Using the given information, please rewrite the text snippet into quote format. Specifically add the following clarifying information in square brackets following the Chicago Manual of Style:
  * Resolve any vague or unclear references in the snippet (e.g. "our approach" or "our method"). Put any clarifying text between brackets. For example "Our approach performs well" becomes "[REF0's] approach [bidirectional language modeling] performs well".
  * Define any specific terminology or acronyms that other scientists will not be familiar with. For example "Our task is MT" becomes "[REF0's] task is MT [machine translation]."
  * If needed, add additional short clarifications that are necessary for an expert reader to understand the broader context of the quote. Only add up to a single sentence and put the sentence in between square brackets.

  After adding clarifying information:
  * Replace first-person pronouns with a placeholder. Replace "we" with "[REF0]" and "our" with "[REF0's]".
  * Remove discourse markers (like "in conclusion", "in this section", "for instance", etc.)
  * Citations are marked as BIBREF or (Author Name, Year). Keep these the same. Do not add any additional citations.
  * Remove any references to Figures ("FIGREF") and Tables ("TABREF")
  * Fix the grammar

  Reminders:
  * Follow the Chicago Manual of Style for quotes by putting all added text between square brackets.
  * The rewritten snippet is a quote, so the word order should closely match the original snippet's.

  Please rewrite this snippet according to the instructions and the given information.
  Text snippet: "{{sentence}}"
  Rewrite: