template: |
  The following "text snippet" will be quoted in an article using the Chicago Manual of Style. Include information in the rewritten snippet to answer the following questions. Add any additions between <add></add> tags. Write as if you were an expert scientist in the field of natural language processing.

  Information from the paper:
  {% for question in questions %}
  Question: {{ question['question'] }}{% endfor %}
  
  Text snippet: "{{sentence}}"

  Instructions:

  Using the given information, please rewrite the text snippet by adding additional information between <add></add> tags.
  For example: the snippet "Our approach performs well" becomes "[REF0's] approach <add>bidirectional language modeling</add> performs well".
  For example: the snippet "Our task is MT" becomes "[REF0's] task is MT <add>machine translation</add>."

  After adding clarifying information:
  * Replace first-person pronouns with a placeholder. Replace "we" with "[REF0]" and "our" with "[REF0's]".
  * Remove discourse markers (like "in conclusion", "in this section", "for instance", etc.)
  * Citations are marked as BIBREF or (Author Name, Year). Keep these the same. Do not add any additional citations.
  * Remove any references to Figures ("FIGREF") and Tables ("TABREF")
  * Fix the grammar

  Reminders:
  * Add ALL new information in between <add></add> tags.
  * Any information in the original snippet should NOT be placed between <add></add> tags.
  * Keep close to the original wording of the snippet

  Please rewrite the snippet according to the instructions and the questions.
  Rewrite: