defaults:
  - defaults
  - _self_

_id: "oa${esc_slash:${.name}}_s${.seed}_ep${.max_epochs}_lr${esc_period:${.lr}}"
lr: 0.05
batch_size: 1
name: "claude-v1"
max_epochs: 1
seed: 1  # Openai doesn't use this, but we do for marking our experiments
interface: "api"
# for_sure_run_train_command_and_spend_dollars: False