defaults:
  - defaults
  - _self_

_id: "mn-${esc_slash:${.name}}_sd-${.seed}_bs-${.batch_size}_ga-${.accumulate_grad_batches}_p${.precision}_ep-${.max_epochs}_lr-${.lr}_wu-${.warmup_ratio}"
batch_size: 2
eval_batch_size: 4
accumulate_grad_batches: 16
precision: 16
lr: 3e-5
warmup_ratio: 0.1
name: "allenai/led-large-16384"
max_epochs: 90
seed: 780