defaults:
  - defaults
  - _self_

_id: "mn-${esc_slash:${.name}}_sd-${.seed}_bs-${.batch_size}_ga-${.accumulate_grad_batches}_ep-${.max_epochs}_lr-${.lr}_wu-${.warmup_ratio}"
batch_size: 1
eval_batch_size: 1
accumulate_grad_batches: 16
lr: 3e-5
warmup_ratio: 0.1
name: "google/pegasus-multi_news"
max_epochs: 1
seed: 42