interface: pipeline
seed: 828
_id: "QGEN-${.qgen._id}_QA-${.qa._id}_SYNTH-${.synth._id}"
qgen:
  _id: "${.model}-${.generation}-${hash:${.overrides}}-gld${.use_gold}"
  use_gold: ${..qa.use_gold_evidence}
  model: gpt3-fewshot-qaspar-qgen
  generation: gpt3
  overrides:
    data.train.path: data/qaspar/decontext-question-gen/train.jsonl
    model.few_shot.y_prefix: "Answer:\n -"
qa:
  _id: "${.model}-${.generation}-${.retriever}-${hash:${.overrides}}-glde${.use_gold_evidence}-glda${.use_gold_answers}"
  use_gold_evidence: ${.use_gold_answers}
  use_gold_answers: False
  model: gpt3-fewshot-qaspar-qa
  generation: gpt3
  retriever: tfidf
  overrides:
    model.few_shot.instructions: 'Using the following text taken from a scientific paper, answer the following question about the "text snippet". Ignore irrelevant information. If you cannot find the answer, write "No answer.":'
    model.few_shot.y_prefix: "Answer:"
  metrics:
    - "em"
    - "rouge"
    - "bert_score"
synth:
  _id: "${.model}-${.generation}-${hash:${.overrides}}" 
  model: gpt3-fewshot-qaspar-synth
  generation: gpt3
  overrides:
    model.few_shot.instructions: 'The following text snippet is extracted from a scientific paper. Incorporate the answers to the following questions to clarify the snippet. Only include information in the Snippet, Questions, and Answers in the new snippet you write. All information you add should be between square brackets []. For example, "MT" -> "MT [machine translation]"'