interface: pipeline
seed: 828
_id: "QGEN-${.qgen._id}_QA-${.qa._id}_SYNTH-${.synth._id}"
qgen:
  _id: "${.model}-${.generation}-${hash:${.overrides}}-gld${.use_gold}"
  use_gold: ${..qa.use_gold_evidence}
  data: template-completion-qgen-science
  model: gpt3-curie
  generation: gpt3
  overrides:
    model.name: "text-davinci-003"
  metrics:
    - "em"
    - "rouge"
qa:
  _id: "${.model}-${.generation}-${.retriever}-${hash:${.overrides}}-glde${.use_gold_evidence}-glda${.use_gold_answers}"
  use_gold_evidence: ${.use_gold_answers}
  use_gold_answers: False
  model: gpt3-fewshot-qaspar-qa
  generation: gpt3
  retriever: dense
  overrides:
    model.few_shot.instructions: 'Using the following text taken from a scientific paper, answer the following question about the "text snippet". Ignore irrelevant information. If you cannot find the answer, write "No answer.":'
    model.few_shot.y_prefix: "Answer:"
  metrics:
    - "em"
    - "rouge"
    - "bert_score"
synth:
  _id: "${.model}-${.generation}-${hash:${.overrides}}"
  data: "template-endtoend-tsp"
  model: gpt3-curie
  generation: gpt3-endtoend
  overrides:
    model.name: text-davinci-003
    data.template: "configs/templates/gold_answer_user_intent_no_title_completion.yaml"