defaults:
  - defaults
  - _self_

_id: "mn-${.name}_sd-${.seed}_${.strategy.name}"
name: "gold"
gold_docs_path: "data/qaspar/decontext-qa-retrieval-docs-gold_0-35.json"
seed: 934
interface: "retrieval"
batch_size: 1
strategy:
  name: "all"