defaults:
  - defaults
  - _self_

_id: "mn-${esc_slash:${.name}}_sd-${.seed}_bs-${.batch_size}_ga-${.accumulate_grad_batches}_ep-${.max_epochs}_lr-${.lr}_wu-${.warmup_ratio}"
batch_size: 1
eval_batch_size: 1
accumulate_grad_batches: 1
lr: 1e-4
warmup_ratio: 0.1
name: "google/flan-t5-xl"
# name: "t5-3b"
max_epochs: 25
seed: 780
# precision: bf16