data_path: data/emnlp23/wiki/pipeline/val.jsonl
results_path: "results/pipeline_wiki/notes_${.notes}"
is_wiki: true
notes: null
extraction: null
surface:
  model: gpt3-fewshot-qaspar-surface
  generation: gpt3
  overrides:
    data.train.path: data/qaspar/decontext-surface/not_derived_train.jsonl
qgen:
  data: template-chatgpt3-qgen-wiki
  model: chat-gpt4
  generation: gpt3
  overrides:
    model.name: "gpt-3.5-turbo"
qa:
  model: gpt3-fewshot-qaspar-qa
  generation: gpt3
  retriever: tfidf
  overrides:
    model.few_shot.instructions: 'Using only the following text taken from a Wikipedia page, answer the following question. Ignore irrelevant information. Do not base your answer on any information not in the text. If you cannot find the answer, write "No answer.":'
    model.few_shot.y_prefix: "Answer:"
synth:
  model: gpt3-fewshot-qaspar-synth
  generation: gpt3
  overrides:
    model.few_shot.instructions: 'The following text snippet is extracted from a Wikipedia page. Incorporate the answers to the following questions to clarify the snippet. Only include information in the Snippet, Questions, and Answers in the new snippet you write.'