data_path: data/emnlp23/science/pipeline/val.jsonl
results_path: "results/pipeline/notes_${.notes}/"
is_wiki: false
notes: null
extraction: null
surface:
  model: gpt3-fewshot-qaspar-surface
  generation: gpt3
  overrides:
    data.train.path: data/qaspar/decontext-surface/not_derived_train.jsonl
qgen:
  model: gpt3-fewshot-qaspar-qgen
  generation: gpt3
  overrides:
    data.train.path: data/qaspar/decontext-question-gen/train.jsonl
    model.few_shot.y_prefix: "Answer:\n -"
qa:
  model: gpt3-fewshot-qaspar-qa
  generation: gpt3
  retriever: tfidf
  overrides:
    model.few_shot.instructions: 'Using the following text taken from a scientific paper, answer the following question. Ignore irrelevant information. If you cannot find the answer, write "No answer.":'
    model.few_shot.y_prefix: "Answer:"
synth:
  model: gpt3-fewshot-qaspar-synth
  generation: gpt3
  overrides:
    model.few_shot.instructions: 'The following text snippet is extracted from a scientific paper. Incorporate the answers to the following questions to clarify the snippet. Only include information in the Snippet, Questions, and Answers in the new snippet you write. All information you add should be between square brackets []. For example, "MT" -> "MT [machine translation]"'
metrics:
 - "em"
 - "rouge"
 - "sari"
 - "length_change"
 - "clf"