_id : "t-${.temperature}_topp-${.top_p}_mgl-${.max_tokens}"
temperature: 0.7
top_p: 1.0
max_tokens: 150
metrics:
 - "em"
 - "rouge"
 - "bert_score"
 - "length_change"
 - name: "bert_score"
   post_process: true
 # - "sari"
#  - "p1p2pct"
#  - "question_pct"
#  - name: "filter"
#    model_config: roberta-large
#    input_data_file: ???
#    model_checkpoint_path: ???
# Question generation
#  - "question_pct"
#  - "question_num"
#  - "question_snippet_overlap"