_id: "nb-${.num_beams}_mgl-${.max_gen_length}"
num_beams: 5
max_gen_length: 150
metrics:
 - "em"
 - "rouge"
 - "sari"
 - "length_change"
 - "clf"
 - name: "bert_score"
   post_process: true
#  - "em"
#  - "rouge"
#  - "bert_score"
#  - "p1p2pct"
#  - "1st_pers_pct"